### ISSUE TITLE
More robust enforcement of Switches requiring two conditions

### ISSUE THREAD

**Issue by stites** [Sentenai/py-sentenai#16]
Motivating example:

```python
sp1 = span(event(V.foo == 0, V.bar == 1))     # valid library code
str(sp2)   # I get sentenai.exceptions.FlareSyntaxError: Switches must have two conditions
```

Unless there is a special circumstance I'm not understanding, I think the FlareSyntaxError should happen on the first line and not the second.

**Comment by xnomagichash** [comment]
Yes checks should definitely happen earlier. It's bad that it waits until rendering to blow  up.

**Comment by brandly** [comment]
closing because, on `master`, `event(V.foo == 0, V.bar == 1)` immediately throws an error, and on the `during` branch, we now allow unary switches
