### ISSUE TITLE
Error in seemingly equivalent syntax 

### ISSUE THREAD

**Issue by stites** [Sentenai/py-sentenai#17]
I was expecting these to be equivalent syntax, but I'm getting a `sentenai.exceptions.FlareSyntaxError: Switches must have two conditions` in the `__call__` of `Switch`.

```python
s = stream("1")

works = select(start=datetime.now(), end=datetime.now()) \
    .span(s.evt == 1, s.evt == 1) \
    .then(s.evt == 1, s.evt == 1)

evt = event(V.evt == 1, V.evt == 1)
broken = select(start=datetime.now(), end=datetime.now()) \
    .span(s(evt)) \
    .then(s(evt))
```

**Comment by xnomagichash** [comment]
That's because switches require two `event`'s sequenced, not just two conditions in a single event.
You probably wanted:
```
evt = event(V.evt == 1) >> event(V.evt == 1)
```
But you can use multiple conditions in a switch by:
```
evt = event(V.e1 == 5, V.e2 == 6) >> event(V.e1 == 6, V.e2 == 3)
```

**Comment by xnomagichash** [comment]
Added a better error to be more prescriptive about how to fix.
