### ISSUE TITLE
Retrieving value of a view at specific time

### ISSUE THREAD

**Issue by AWildSugar** [Sentenai/py-sentenai#197]
With the values api, we can retrieve the value of a field at a specific time with the @ operator:

`weather['temperatureMax'] @ datetime(2010,6,1)     # or use weather['temperatureMax'].value(at=...)`

There is no simple way to do the same thing with a view - they only work with slices. The best way to sort by descending order, and query from the beginning of the stream to the time of interest with a limit of 1 returned event:

`sentenai.views['test-weather'].data[datetime(2010,9,1):sentenai.streams['weather'].bounds[0]:1]` 

Note the reversed order of the start and end, which flips the sort order ( -1 as the limit is rejected @xnomagichash)
We'd like to add syntactic sugar for this - i.e. make it possible to do 

`sentenai.views['test-weather'].data[datetime(2010,9,1)]`

First though, there is the issue that the verbose query returns an error because it expects a np.datetime64, which is easy enough to fix by adding

```          
                params['start'] = np.datetime64(params['start'])
                params['end'] = np.datetime64(params['end'])
```

to the "reverse time order if necessary" block around line 194 of views.py, though I can't say if that's the best way of doing things yet. 

Then, adding the new indexing looks like it'll be just be a case in __getitem__ for Data in views.

**Comment by xnomagichash** [comment]
I would propose we use the `@` operator consistently between views and values.

**Comment by AWildSugar** [comment]
That's makes sense to me, but to play devil's advocate - @ operator is rather obscure, I had definitely never seen it before - and it's not very pandas-like (or atleast it's not coming up on google) so I'd propose atleast doing both if we're going to support slices too.

Though maybe there are advantages to @ I don't know about?

**Comment by xnomagichash** [comment]
slices don't work in this case because there are not necessarily events at the timestamp you're asking for. The @ convention is from elsewhere b/c pandas doesn't have this concept.
