### ISSUE TITLE
`limit` is close but not always perfect

### ISSUE THREAD

**Issue by brandly** [Sentenai/py-sentenai#60]
just ran a spans query a couple times with `limit=100` and received `105` and then `104` results

**Comment by xnomagichash** [comment]
That's because we currently can't return exact number of events if multiple events in a stream have the same timestamp. This is actually a corona problem that mitchell is working on.

**Comment by mitchellwrosen** [comment]
@brandly Were you getting spans or events?

**Comment by brandly** [comment]
spans! i think it's a client bug, but i haven't dug into it yet
