### ISSUE TITLE
threadpool seems to be tied to the number of spans when it should be a higher fidelity 

### ISSUE THREAD

**Issue by stites** [Sentenai/py-sentenai#65]
I am seeing sub-second query results in Corona, but downloading the query takes >40m. I think this is because of the above (the threadpool seems to be tied to the number of spans) -- I'm thinking we should crank up the concurrency by returning tagged 1h windows and merging the results. This is a little primitive, isn't event-aware, and could use some fine-tuning, so I'm definitely open to discussion. That said, I am already working on a fix to make things more usable on my end.

**Comment by xnomagichash** [comment]
There's no benefit to increasing parallelism, as high parallelism actually slows downloads down in practice and we throttle high levels of parallelism on the cluster to protect availability.

**Comment by stites** [comment]
yeah, I also realized that it doesn't matter if we increase the parallelism if the network is slow (also yes, having too many threads seems like it would block the NIC as well). I think a better solution is something like in #67 where we start talking about features regarding the responsiveness of the client.
