### ISSUE TITLE
Research dask support

### ISSUE THREAD

**Issue by stites** [sentenai/py-sentenai#66]
Most queries I am working with are large enough to stall my laptop. Since py-sentenai is a numpy/pandas frontend, we should look into dask to support a common API with multithreaded support. Numba support should also be checked out.

**Comment by xnomagichash** [comment]
We should definitely support something like Dask on the cluster side so data doesn't have to move as far.

**Comment by stites** [comment]
Yup. I was thinking of that as well -- dask seems about as unopinionated as you can get in python land. Another alternative is implementing a Spark RDD interface (but I think that might require more leg-work). I know we were talking about spinning up an aggregation server -- perhaps this is that solution for the short-term.
