### ISSUE TITLE
Show a progress bar when fetching events.

### ISSUE THREAD

**Issue by stites** [sentenai/py-sentenai#67]

**Comment by stites** [comment]
good to know! I've renamed this issue so that it's more actionable. There are two more issues I think we should discuss separately.

For progress bars, this would necessitate switching from `json.dumps` to a streaming json library.

**Comment by brandly** [comment]
> There's no way to make progress bars compatible with the terminal that don't crash jupyter notebooks.

i think @selik mentioned that we could use `logging` to make things terminal/jupyter compatible

**Comment by stites** [comment]
Another option I was thinking of for jupyter notebooks is to use an notebook-specific widget. Something like https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#IntProgress

![2018-04-05-153710_533x238_scrot](https://user-images.githubusercontent.com/1694705/38387826-331ffa12-38e7-11e8-9926-47ee1b921893.png)
