### ISSUE TITLE
Add support for `returning` argument to `ast` function

### ISSUE THREAD

**Issue by xnomagichash** [Sentenai/py-sentenai#7]
Currently replacing `sentenai.query` with `ast` only works if `returning` is not present in the query. Debugging will be a lot easier if we allow `returning` to be an argument to `ast` (and this will also be more correct).

**Comment by brandly** [comment]
this works nowadays: https://github.com/Sentenai/py-sentenai/blob/master/tests/flare/test_ast.py#L354-L361
